// Illustration emoji for each card — displayed in empty icon slots.
(function (root) {
  root.CARD_ILLUST = {
    // ─── Age 1 ───────────────────────────────────────────────
    pottery:       '🏺',
    tools:         '🔨',
    writing:       '✏️',
    archery:       '🏹',
    metalworking:  '⚒️',
    oars:          '🚣',
    clothing:      '👘',
    sailing:       '⛵',
    the_wheel:     '☸️',
    agriculture:   '🌾',
    domestication: '🐄',
    masonry:       '🏛️',
    city_states:   '🏙️',
    code_of_laws:  '⚖️',
    mysticism:     '🔮',
    // ─── Age 2 ───────────────────────────────────────────────
    calendar:      '📅',
    mathematics:   '📐',
    construction:  '🏗️',
    road_building: '🛣️',
    currency:      '💰',
    mapmaking:     '🗺️',
    canal_building:'🚢',
    fermenting:    '🍺',
    monotheism:    '⛪',
    philosophy:    '💭',
    // ─── Age 3 ───────────────────────────────────────────────
    alchemy:       '⚗️',
    translation:   '📜',
    engineering:   '🔩',
    optics:        '🔭',
    compass:       '🧭',
    paper:         '📄',
    machinery:     '⚙️',
    medicine:      '💊',
    education:     '🎓',
    feudalism:     '⚔️',
    // ─── Age 4 ───────────────────────────────────────────────
    experimentation: '🧪',
    printing_press:  '📰',
    colonialism:     '⚓',
    gunpowder:       '💣',
    invention:       '💡',
    navigation:      '🗺️',
    anatomy:         '🦴',
    perspective:     '🎨',
    enterprise:      '💼',
    reformation:     '⛪',
    // ─── Age 5 ───────────────────────────────────────────────
    chemistry:     '⚗️',
    physics:       '⚛️',
    coal:          '⛏️',
    pirate_code:   '⚓',
    banking:       '🏦',
    measurement:   '📏',
    statistics:    '📊',
    steam_engine:  '🚂',
    astronomy:     '🌟',
    societies:     '👥',
    // ─── Age 6 ───────────────────────────────────────────────
    atomic_theory:    '⚛️',
    encyclopedia:     '📚',
    industrialization:'🏭',
    machine_tools:    '🔧',
    classification:   '🔬',
    metric_system:    '📏',
    canning:          '🥫',
    vaccination:      '💉',
    democracy:        '🗳️',
    emancipation:     '✊',
    // ─── Age 7 ───────────────────────────────────────────────
    evolution:     '🦎',
    publication:   '📰',
    combustion:    '🔥',
    explosives:    '💥',
    bicycle:       '🚲',
    electricity:   '⚡',
    refrigeration: '❄️',
    sanitation:    '🚿',
    lighting:      '💡',
    railroad:      '🛤️',
    // ─── Age 8 ───────────────────────────────────────────────
    quantum_theory: '⚛️',
    rocketry:       '🚀',
    flight:         '✈️',
    mobility:       '🚗',
    corporations:   '🏢',
    mass_media:     '📺',
    antibiotics:    '💊',
    skyscrapers:    '🌆',
    empiricism:     '📋',
    socialism:      '🚩',
    // ─── Age 9 ───────────────────────────────────────────────
    computers:      '💻',
    genetics:       '🧬',
    composites:     '🧱',
    fission:        '☢️',
    collaboration:  '🤝',
    satellites:     '📡',
    ecology:        '🌿',
    suburbia:       '🏘️',
    services:       '🛎️',
    specialization: '🎯',
    // ─── Age 10 ──────────────────────────────────────────────
    bioengineering: '🧬',
    software:       '💾',
    miniaturization:'💎',
    robotics:       '🤖',
    databases:      '🗂️',
    self_service:   '🏪',
    globalization:  '🌐',
    stem_cells:     '🧫',
    ai:             '🤖',
    the_internet:   '🌐'
  };
})(typeof self !== 'undefined' ? self : this);
