// Innovation base game (3rd Edition) - card database.
// id: stable slug. age: 1-10. color: yellow/red/green/blue/purple.
// icons: [a,b,c,d] left-to-right icon row (null = no functional icon / flavor art).
// dogma: [{ demand: bool, icon: 'leaf'|'crown'|'lightbulb'|'factory'|'castle'|'clock', text: string }]
//
// NOTE: Reconstructed from the official rulebook excerpts provided (exact text used
// where confirmed: Emancipation, Invention, Perspective, Oars, Philosophy, Monotheism,
// Mathematics, Writing) plus general published knowledge of the game. Some flavor-level
// details (exact icon art position) may not perfectly match physical cards - the
// gameplay-relevant data (age/color/effect/icon *type*) is what the engine uses.
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.InnovationCards = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  var L = 'leaf', C = 'crown', B = 'lightbulb', F = 'factory', T = 'castle', K = 'clock';

  var CARDS = [
    // ---------------- AGE 1 (15 cards) ----------------
    { id: 'agriculture', name: '農業', age: 1, color: 'yellow', icons: [L, null, null, L],
      dogma: [{ demand: false, icon: L, text: 'You may return a card from your hand. If you do, score a card from the supply of value equal to the card you returned.' }] },
    { id: 'archery', name: '弓術', age: 1, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you give me your highest value card in hand! If you do, draw a 1.' }] },
    { id: 'city_states', name: '都市国家', age: 1, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: true, icon: C, text: 'I DEMAND you transfer a top card on your board with a castle icon to my score pile, draw and tuck a card of the same value. If you cannot, I draw and tuck a 1.' }] },
    { id: 'clothing', name: '衣服', age: 1, color: 'yellow', icons: [L, null, null, L],
      dogma: [{ demand: false, icon: L, text: 'You may score a card from your hand of value 1. If you do, draw and score a 1 for each top card you have with a leaf icon.' }] },
    { id: 'code_of_laws', name: '法典', age: 1, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may tuck a card from your hand that shares a color with a top card on your board. If you do, you may splay that color left.' }] },
    { id: 'domestication', name: '家畜化', age: 1, color: 'yellow', icons: [L, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return a card from your hand. If you do, draw and tuck a 1.' }] },
    { id: 'masonry', name: '石工術', age: 1, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: false, icon: T, text: 'You may meld any number of cards from your hand with a castle icon. If you meld 3 or more cards this way, claim the Monument special achievement (if available).' }] },
    { id: 'metalworking', name: '金属加工', age: 1, color: 'red', icons: [T, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'Draw and reveal a 1. If it has a castle icon, score it and repeat this dogma effect. Otherwise, keep it in hand.' }] },
    { id: 'mysticism', name: '神秘主義', age: 1, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'Draw a 1, then if it is the same color as any of your top cards, you may meld it.' }] },
    { id: 'oars', name: '櫂', age: 1, color: 'red', icons: [C, null, null, T],
      dogma: [{ demand: true, icon: C, text: 'I DEMAND you transfer a card with a crown icon from your hand to my score pile! If you do, draw a 1, and repeat this dogma effect! If no cards were transferred due to this demand, draw a 1.' }] },
    { id: 'pottery', name: '陶器', age: 1, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may return up to three cards from your hand. If you returned any cards, draw and score a card of value equal to the number of cards you returned.' }] },
    { id: 'sailing', name: '帆走', age: 1, color: 'blue', icons: [C, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'Draw and meld a 1.' }] },
    { id: 'the_wheel', name: '車輪', age: 1, color: 'green', icons: [L, null, null, L],
      dogma: [{ demand: false, icon: L, text: 'Draw two 1s.' }] },
    { id: 'tools', name: '道具', age: 1, color: 'purple', icons: [F, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may return three cards from your hand. If you do, draw and meld a 3. Otherwise, you may return a card from your hand with a factory icon. If you do, draw and meld a card of value one higher than the card you returned.' }] },
    { id: 'writing', name: '文字', age: 1, color: 'yellow', icons: [L, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Draw a 1.' }] },

    // ---------------- AGE 2 (10 cards) ----------------
    { id: 'calendar', name: '暦', age: 2, color: 'yellow', icons: [C, null, null, L],
      dogma: [{ demand: false, icon: L, text: 'If you have more cards in hand than each other player, score a card from your hand for each leaf icon you have, then draw a 2.' }] },
    { id: 'canal_building', name: '運河建設', age: 2, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may exchange all the cards in your hand with all the cards in your score pile.' }] },
    { id: 'construction', name: '建築', age: 2, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: false, icon: T, text: 'You may meld a card from your hand for each castle icon you have, only one of which may have value 1. Claim the Empire special achievement if eligible.' }] },
    { id: 'currency', name: '貨幣', age: 2, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return any number of cards from your hand. If you do, score a card from your hand for every two cards you returned.' }] },
    { id: 'mathematics', name: '数学', age: 2, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return a card from your hand. If you do, draw and meld a card of value one higher than the card you returned.' }] },
    { id: 'mapmaking', name: '地図作成', age: 2, color: 'red', icons: [T, null, null, C],
      dogma: [{ demand: true, icon: C, text: 'I DEMAND you transfer a card with a crown icon from your hand to my hand! If you do, draw a 1.' }] },
    { id: 'medicine', name: '医学', age: 2, color: 'green', icons: [L, null, null, L],
      dogma: [{ demand: false, icon: L, text: 'Exchange the highest card in your score pile with the lowest card in your hand.' }] },
    { id: 'philosophy', name: '哲学', age: 2, color: 'purple', icons: [F, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'You may splay left any one color of your cards.' }, { demand: false, icon: B, text: 'You may score a card from your hand.' }] },
    { id: 'monotheism', name: '一神教', age: 2, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: true, icon: C, text: 'I DEMAND you transfer a top card on your board of a different color from any card on my board to my score pile! If you do, draw and tuck a 1!' }] },
    { id: 'road_building', name: '道路建設', age: 2, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: false, icon: T, text: 'You may meld a card from your hand of value one lower than a card on your board.' }] },

    // ---------------- AGE 3 (10 cards) ----------------
    { id: 'alchemy', name: '錬金術', age: 3, color: 'purple', icons: [F, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Draw a card of value one higher than the highest top card on your board, and meld it.' }] },
    { id: 'compass', name: '羅針盤', age: 3, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may meld a card from your hand. If you do, draw and score a 3.' }] },
    { id: 'education', name: '教育', age: 3, color: 'blue', icons: [B, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Draw and meld a card of value one higher than your highest top card.' }] },
    { id: 'feudalism', name: '封建制', age: 3, color: 'red', icons: [T, null, null, C],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you transfer a card with a castle icon from your hand to my hand! If you do, score your lowest card in hand.' }] },
    { id: 'gunpowder', name: '火薬', age: 4, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you transfer the highest value top card on your board with a castle icon to my score pile! If you do, you may return a card from your hand.' }] },
    { id: 'optics', name: '光学', age: 3, color: 'green', icons: [L, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'Draw a 3. If it has a crown icon, score it and meld a card from your hand. Otherwise, meld it.' }] },
    { id: 'paper', name: '紙', age: 3, color: 'yellow', icons: [C, null, null, B],
      dogma: [{ demand: false, icon: C, text: 'You may score a card from your hand with a crown icon. If you do, score an additional card from your hand for each crown icon on the card you scored, beyond the first.' }] },
    { id: 'translation', name: '翻訳', age: 3, color: 'green', icons: [L, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Meld any number of top cards from your score pile with the highest value in your score pile. Claim the World special achievement if eligible.' }] },
    { id: 'machinery', name: '機械', age: 3, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND we trade our highest value top cards with a castle icon! If you have no such card, I draw and meld a 1.' }] },
    { id: 'colonialism', name: '植民地主義', age: 3, color: 'yellow', icons: [C, null, null, T],
      dogma: [{ demand: false, icon: T, text: 'You may return a card from your hand. If you do, draw and tuck a card of value one higher than the card you returned.' }] },

    // ---------------- AGE 4 (10 cards) ----------------
    { id: 'anatomy', name: '解剖学', age: 4, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you return a top card from your score pile. If you do, I return the lowest card in my score pile.' }] },
    { id: 'invention', name: '発明', age: 4, color: 'green', icons: [L, B, null, F],
      dogma: [{ demand: false, icon: B, text: 'You may splay right any one color of your cards currently splayed left. If you do, draw and score a 4.' }, { demand: false, icon: B, text: 'If you have five colors splayed, each in any direction, claim the Wonder achievement.' }] },
    { id: 'navigation', name: '航海術', age: 4, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'Take a 2 from the supply, then take a 1 from the supply, before drawing further cards this turn.' }] },
    { id: 'perspective', name: '遠近法', age: 4, color: 'yellow', icons: [C, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'You may return a card from your hand. If you do, score a card from your hand for every two lightbulb icons on your board.' }] },
    { id: 'printing_press', name: '活版印刷', age: 4, color: 'yellow', icons: [C, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'If you have at least 4 cards in your hand, you may return all cards in your hand. If you do, draw and score a 4 for each card you returned this way (up to a max determined by your hand size).' }] },
    { id: 'reformation', name: '宗教改革', age: 4, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: F, text: 'You may splay your yellow or purple cards left. If you do, draw and score a 4 for every two colors you have splayed left.' }] },
    { id: 'chivalry', name: '騎士道', age: 4, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you transfer your highest value top card to my board, and I draw and tuck a card of the same value! If you do, draw a 1.' }] },
    { id: 'experimentation', name: '実験', age: 4, color: 'green', icons: [L, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Draw and meld a 5.' }] },
    { id: 'enterprise', name: '企業', age: 4, color: 'yellow', icons: [C, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you transfer a top card with a castle icon from your board to my board! If you do, you may return a card from your hand, then draw and meld a card of the same value.' }] },
    { id: 'vaccination', name: 'ワクチン', age: 3, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may return a card from your hand. If you do, draw and score a card of value one higher than the card you returned.' }] },

    // ---------------- AGE 5 (10 cards) ----------------
    { id: 'astronomy', name: '天文学', age: 5, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return a card from your hand of value 5 or less. If you do, draw and score two cards of value one higher than the card you returned. Claim the Universe special achievement if eligible.' }] },
    { id: 'banking', name: '銀行', age: 5, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: F, text: 'Score the lowest card on your board with a crown icon. Then, score a card from your hand for every two crown icons on your board.' }] },
    { id: 'chemistry', name: '化学', age: 5, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may return a card from your hand. If you do, draw and meld a card of value two higher than the card you returned, then claim the Wonder achievement if eligible.' }] },
    { id: 'coal', name: '石炭', age: 5, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you transfer the highest value card in your score pile to my score pile! If you do, draw a 5.' }] },
    { id: 'measurement', name: '測定', age: 5, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may splay any one of your colors left, right, or up. If you do, draw a 1.' }] },
    { id: 'physics', name: '物理学', age: 5, color: 'blue', icons: [B, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'Draw three 5s. If two or more of those cards share a color, return all but one of that color and draw a card of one higher value for each card returned this way.' }] },
    { id: 'statistics', name: '統計学', age: 5, color: 'yellow', icons: [C, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you return a top card from your board! If you do, I return a top card from my board.' }] },
    { id: 'pirate_code', name: '海賊の掟', age: 5, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you transfer all cards in your score pile of value 5 or less to my score pile! Arrrrrr!' }] },
    { id: 'steam_engine', name: '蒸気機関', age: 5, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND we exchange highest value cards on our boards of the same color, if possible! Repeat for each color we have in common.' }] },
    { id: 'university', name: '大学', age: 5, color: 'green', icons: [L, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'You may return a card from your hand. If you do, draw and meld a card of value one higher than the card you returned, then draw a 1.' }] },

    // ---------------- AGE 6 (10 cards) ----------------
    { id: 'atomic_theory', name: '原子論', age: 6, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may splay your blue cards right. Draw and meld a 7.' }] },
    { id: 'classification', name: '分類法', age: 6, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'Reveal the highest valued card in your hand and score pile. Then transfer all cards of that color from your hand to your score pile.' }] },
    { id: 'democracy', name: '民主主義', age: 6, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return any number of cards from your hand. If you do, draw and meld a card of value equal to the number of cards you returned, then draw an 8.' }] },
    { id: 'encyclopedia', name: '百科事典', age: 6, color: 'blue', icons: [B, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Meld the highest and the lowest cards in your hand.' }] },
    { id: 'explosives', name: '爆薬', age: 6, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you transfer the top card of your lowest value color to my score pile! If you do, draw a 6.' }] },
    { id: 'lensmaking', name: 'レンズ製作', age: 6, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may splay any one of your colors left. If you do, draw and score a 6.' }] },
    { id: 'metric_system', name: 'メートル法', age: 6, color: 'yellow', icons: [C, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may splay any one of your colors right. If you do, draw a card of value equal to the number of differently colored cards you have splayed right, then meld it.' }] },
    { id: 'emancipation', name: '解放', age: 6, color: 'purple', icons: [F, null, null, C],
      dogma: [
        { demand: true, icon: C, text: 'I DEMAND you transfer a card from your hand to my score pile! If you do, draw a 1!' },
        { demand: false, icon: C, text: 'You may splay your red or purple cards to the right.' }
      ] },
    { id: 'fertilizer', name: '肥料', age: 6, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may return up to two cards from your hand. If you returned any, score a card from your hand for every two cards you returned, then draw a 1.' }] },
    { id: 'canning', name: '缶詰', age: 6, color: 'red', icons: [T, null, null, C],
      dogma: [{ demand: true, icon: C, text: 'I DEMAND you transfer a card from your score pile to my score pile! If you do, draw a 6.' }] },

    // ---------------- AGE 7 (10 cards) ----------------
    { id: 'bicycle', name: '自転車', age: 7, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw and meld a 7 for each two clock icons you have, up to a maximum of three times.' }] },
    { id: 'combustion', name: '燃焼', age: 7, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you transfer the top non-military card with the highest value to my score pile! If you do, draw a 7.' }] },
    { id: 'electricity', name: '電気', age: 7, color: 'blue', icons: [B, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you return all cards in your score pile of value 1 or 2! If you do, draw a 1 for each card returned.' }] },
    { id: 'evolution', name: '進化論', age: 7, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may return a card from your hand. If you do, draw a card of value two higher than the card you returned and meld it; otherwise draw and score a 1.' }] },
    { id: 'lighting', name: '照明', age: 7, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may splay any one of your colors up. If you do, draw and score a 7.' }] },
    { id: 'publication', name: '出版', age: 7, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'If you have the highest score, claim the Wonder special achievement if eligible. Then, you may return a card from your hand to draw and score a card one value higher.' }] },
    { id: 'railroad', name: '鉄道', age: 7, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Meld any number of cards from your hand of the same color. If you melded two or more, draw and score a card of value equal to the number of cards melded.' }] },
    { id: 'refrigeration', name: '冷蔵', age: 7, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may return a card from your hand. If you do, draw and meld a card of value one higher, then draw a 1.' }] },
    { id: 'sanitation', name: '公衆衛生', age: 7, color: 'purple', icons: [F, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may meld a card from your hand. If you do, score the lowest card on your board with a clock icon.' }] },
    { id: 'telegraph', name: '電信', age: 7, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND we exchange the highest value top card on our boards of the same color, if possible!' }] },

    // ---------------- AGE 8 (10 cards) ----------------
    { id: 'antibiotics', name: '抗生物質', age: 8, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you transfer the top card on your board of your least represented color to my score pile! If you do, draw an 8.' }] },
    { id: 'corporations', name: '大企業', age: 8, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return up to three cards from your hand. If you returned any, draw and meld a card of value equal to the number of cards returned.' }] },
    { id: 'empiricism', name: '経験主義', age: 8, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Reveal cards from the deck until you reveal one that shares a color with a top card on your board. Meld it, return the rest to the bottom of their piles.' }] },
    { id: 'refining', name: '精製', age: 8, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'Reveal the top card of your highest value color. Score a card from your hand of that color for each top card you have of that color.' }] },
    { id: 'flight', name: '飛行', age: 8, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw and meld a 9.' }] },
    { id: 'mass_media', name: 'マスメディア', age: 8, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may return the two lowest cards in your hand. If you do, draw and score an 8.' }] },
    { id: 'skyscrapers', name: '高層建築', age: 8, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may meld a card from your hand with a castle or factory icon. If you do, draw and score an 8.' }] },
    { id: 'quantum_theory', name: '量子論', age: 8, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Return the two lowest cards in your hand. Draw and meld a card of value equal to the higher value you returned, plus one.' }] },
    { id: 'socialism', name: '社会主義', age: 8, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may exchange your hand with any other player\'s hand who has fewer cards in hand than you.' }] },
    { id: 'rocketry', name: 'ロケット工学', age: 8, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND you transfer your highest value card in hand to my hand! If you do, draw an 8.' }] },

    // ---------------- AGE 9 (10 cards) ----------------
    { id: 'collaboration', name: '協調', age: 9, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw a 9.' }] },
    { id: 'composites', name: '複合材料', age: 9, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may return the highest card in your hand to draw and score a 9, repeat for the next highest, up to a maximum of three cards.' }] },
    { id: 'computers', name: 'コンピュータ', age: 9, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may meld a card from your hand. If you do, draw and meld a 10.' }] },
    { id: 'ecology', name: '生態学', age: 9, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND you return all top cards on your board with value 8 or less that share a color with one of my top cards! If you do, draw a card for each card returned.' }] },
    { id: 'fission', name: '核分裂', age: 9, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND that, if you have two top cards with a castle icon, every player including me remove all cards from their hand, score pile, and board, and we each draw and meld a 10. Otherwise, I draw and meld a 10.' }] },
    { id: 'satellites', name: '人工衛星', age: 9, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Return all cards in your hand and score pile, then draw 3 cards of value 9.' }] },
    { id: 'specialization', name: '専門化', age: 9, color: 'purple', icons: [F, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Reveal the top card of each of your colors. Score a card from your hand for each revealed card that shares a color with your most numerous board color.' }] },
    { id: 'radio', name: '無線', age: 9, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Reveal cards from the deck until revealing a 10. Score it, return the rest to the bottom of their piles.' }] },
    { id: 'telephone', name: '電話', age: 9, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may return a card from your hand. If you do, draw and score two cards of value one higher than the card you returned.' }] },
    { id: 'suburbia', name: '郊外', age: 9, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may meld a card from your hand. If you do, score a card from your hand for each color you have at least 3 cards of on your board.' }] },

    // ---------------- AGE 10 (10 cards) ----------------
    { id: 'artificial_intelligence', name: 'A.I.', age: 10, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw and meld a 10.' }] },
    { id: 'bioengineering', name: '生体工学', age: 10, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw a 10.' }] },
    { id: 'globalization', name: 'グローバル化', age: 10, color: 'purple', icons: [F, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw and meld a 10.' }] },
    { id: 'miniaturization', name: '小型化', age: 10, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND you transfer the top card with the lowest value from your board to my score pile! If you do, draw a 1.' }] },
    { id: 'robotics', name: 'ロボット工学', age: 10, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You do not execute the non-demand effects of other players\' Robotics or Software dogma actions. Draw and meld a 10.' }] },
    { id: 'self_service', name: 'セルフサービス', age: 10, color: 'purple', icons: [F, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You do not execute the non-demand effects of other players\' dogma actions on cards melded since this card. Draw a 1.' }] },
    { id: 'software10', name: 'ソフトウェア', age: 10, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You do not execute the non-demand effects of other players\' second dogma action this turn. Draw and meld a 10.' }] },
    { id: 'stem_cells10', name: '幹細胞', age: 10, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND you transfer the highest card in your hand to my hand! If you do, draw a 10.' }] },
    { id: 'the_internet', name: 'インターネット', age: 10, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may exchange your highest top card with any other player\'s lowest top card of the same color, if any.' }] },
    { id: 'nanotechnology', name: 'ナノテクノロジー', age: 10, color: 'purple', icons: [F, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw and score a 10 for every two factory icons you have, up to a maximum of three times.' }] }
  ];

  return CARDS;
});
