// Innovation base game (3rd Edition) - card database.
// id: stable slug. age: 1-10. color: yellow/red/green/blue/purple.
// icons: [a,b,c,d] left-to-right icon row (null = no functional icon / flavor art).
// dogma: [{ demand: bool, icon: 'leaf'|'crown'|'lightbulb'|'factory'|'castle'|'clock', text: string }]
//
// NOTE: Reconstructed from the official rulebook excerpts provided (exact text used
// where confirmed: Emancipation, Invention, Perspective, Oars, Philosophy, Monotheism,
// Mathematics, Writing) plus general published knowledge of the game. Some flavor-level
// details (exact icon art position) may not perfectly match physical cards - the
// gameplay-relevant data (age/color/effect/icon *type*) is what the engine uses.
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.InnovationCards = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  var L = 'leaf', C = 'crown', B = 'lightbulb', F = 'factory', T = 'castle', K = 'clock';

  var CARDS = [
    // ---------------- AGE 1 (15 cards) ----------------
    { id: 'agriculture', name: '農業', age: 1, color: 'yellow', icons: [L, null, null, L],
      dogma: [{ demand: false, icon: L, text: 'You may return a card from your hand. If you do, score a card from the supply of value equal to the card you returned.', textJa: 'あなたは手札からカードを1枚戻してもよい。戻した場合、戻したカードと同じ価値のカードを補充パイルから得点する。' }] },
    { id: 'archery', name: '弓術', age: 1, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you give me your highest value card in hand! If you do, draw a 1.', textJa: '【強制】対象プレイヤーは、手札の最高値カードをあなたに渡す。渡した場合、対象プレイヤーは1を引く。' }] },
    { id: 'city_states', name: '都市国家', age: 1, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: true, icon: C, text: 'I DEMAND you transfer a top card on your board with a castle icon to my score pile, draw and tuck a card of the same value. If you cannot, I draw and tuck a 1.', textJa: '【強制】対象プレイヤーは、ボードの一番上にある城アイコン付きカードをあなたの得点パイルに渡し、同じ価値のカードを引いてタックする。渡せない場合、あなたが1を引いてタックする。' }] },
    { id: 'clothing', name: '衣服', age: 1, color: 'yellow', icons: [L, null, null, L],
      dogma: [{ demand: false, icon: L, text: 'You may score a card from your hand of value 1. If you do, draw and score a 1 for each top card you have with a leaf icon.', textJa: 'あなたは手札から価値1のカードを得点してもよい。した場合、葉アイコンを持つ一番上のカード1枚につき1を引いて得点する。' }] },
    { id: 'code_of_laws', name: '法典', age: 1, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may tuck a card from your hand that shares a color with a top card on your board. If you do, you may splay that color left.', textJa: 'あなたは、ボードの一番上のカードと同じ色のカードを手札からタックしてもよい。した場合、その色を左にスプレイしてもよい。' }] },
    { id: 'domestication', name: '家畜化', age: 1, color: 'yellow', icons: [L, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return a card from your hand. If you do, draw and tuck a 1.', textJa: 'あなたは手札からカードを1枚戻してもよい。した場合、1を引いてタックする。' }] },
    { id: 'masonry', name: '石工術', age: 1, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: false, icon: T, text: 'You may meld any number of cards from your hand with a castle icon. If you meld 3 or more cards this way, claim the Monument special achievement (if available).', textJa: 'あなたは手札の城アイコン付きカードを好きな数メルドしてもよい。この方法で3枚以上メルドした場合、記念碑特別達成カード（残っていれば）を獲得する。' }] },
    { id: 'metalworking', name: '金属加工', age: 1, color: 'red', icons: [T, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'Draw and reveal a 1. If it has a castle icon, score it and repeat this dogma effect. Otherwise, keep it in hand.', textJa: '1を引いて公開する。城アイコンを持っていれば、それを得点してこの効果を繰り返す。持っていなければ、手札に加える。' }] },
    { id: 'mysticism', name: '神秘主義', age: 1, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'Draw a 1, then if it is the same color as any of your top cards, you may meld it.', textJa: '1を引く。それがあなたの一番上のカードのいずれかと同じ色であれば、メルドしてもよい。' }] },
    { id: 'oars', name: '櫂', age: 1, color: 'red', icons: [C, null, null, T],
      dogma: [{ demand: true, icon: C, text: 'I DEMAND you transfer a card with a crown icon from your hand to my score pile! If you do, draw a 1, and repeat this dogma effect! If no cards were transferred due to this demand, draw a 1.', textJa: '【強制】対象プレイヤーは、王冠アイコン付きカードを手札からあなたの得点パイルに渡す。渡した場合、対象プレイヤーは1を引き、この効果を繰り返す。この要求で渡せなかった場合、あなたが1を引く。' }] },
    { id: 'pottery', name: '陶器', age: 1, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may return up to three cards from your hand. If you returned any cards, draw and score a card of value equal to the number of cards you returned.', textJa: 'あなたは手札から最大3枚のカードを戻してもよい。1枚以上戻した場合、戻した枚数と同じ価値のカードを引いて得点する。' }] },
    { id: 'sailing', name: '帆走', age: 1, color: 'blue', icons: [C, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'Draw and meld a 1.', textJa: '1を引いてメルドする。' }] },
    { id: 'the_wheel', name: '車輪', age: 1, color: 'green', icons: [L, null, null, L],
      dogma: [{ demand: false, icon: L, text: 'Draw two 1s.', textJa: '1を2枚引く。' }] },
    { id: 'tools', name: '道具', age: 1, color: 'purple', icons: [F, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may return three cards from your hand. If you do, draw and meld a 3. Otherwise, you may return a card from your hand with a factory icon. If you do, draw and meld a card of value one higher than the card you returned.', textJa: 'あなたは手札から3枚のカードを戻してもよい。した場合、3を引いてメルドする。そうしなかった場合、手札から工場アイコン付きカードを1枚戻してもよい。した場合、戻したカードより価値が1高いカードを引いてメルドする。' }] },
    { id: 'writing', name: '文字', age: 1, color: 'yellow', icons: [L, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Draw a 1.', textJa: '1を引く。' }] },

    // ---------------- AGE 2 (10 cards) ----------------
    { id: 'calendar', name: '暦', age: 2, color: 'yellow', icons: [C, null, null, L],
      dogma: [{ demand: false, icon: L, text: 'If you have more cards in hand than each other player, score a card from your hand for each leaf icon you have, then draw a 2.', textJa: '他のすべてのプレイヤーより手札が多ければ、あなたが持つ葉アイコン1つにつき手札からカードを1枚得点し、その後2を引く。' }] },
    { id: 'canal_building', name: '運河建設', age: 2, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may exchange all the cards in your hand with all the cards in your score pile.', textJa: 'あなたは手札のカードすべてを得点パイルのカードすべてと交換してもよい。' }] },
    { id: 'construction', name: '建築', age: 2, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: false, icon: T, text: 'You may meld a card from your hand for each castle icon you have, only one of which may have value 1. Claim the Empire special achievement if eligible.', textJa: 'あなたが持つ城アイコン1つにつき、手札からカードを1枚メルドしてもよい（価値1のカードは1枚まで）。条件を満たせば帝国特別達成カードを獲得する。' }] },
    { id: 'currency', name: '貨幣', age: 2, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return any number of cards from your hand. If you do, score a card from your hand for every two cards you returned.', textJa: 'あなたは手札から好きな数のカードを戻してもよい。した場合、戻した枚数2枚につき手札からカードを1枚得点する。' }] },
    { id: 'mathematics', name: '数学', age: 2, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return a card from your hand. If you do, draw and meld a card of value one higher than the card you returned.', textJa: 'あなたは手札からカードを1枚戻してもよい。した場合、戻したカードより価値が1高いカードを引いてメルドする。' }] },
    { id: 'mapmaking', name: '地図作成', age: 2, color: 'red', icons: [T, null, null, C],
      dogma: [{ demand: true, icon: C, text: 'I DEMAND you transfer a card with a crown icon from your hand to my hand! If you do, draw a 1.', textJa: '【強制】対象プレイヤーは、王冠アイコン付きカードを手札からあなたの手札に渡す。渡した場合、対象プレイヤーは1を引く。' }] },
    { id: 'medicine', name: '医学', age: 2, color: 'green', icons: [L, null, null, L],
      dogma: [{ demand: false, icon: L, text: 'Exchange the highest card in your score pile with the lowest card in your hand.', textJa: '得点パイルの最高値カードと、手札の最低値カードを交換する。' }] },
    { id: 'philosophy', name: '哲学', age: 2, color: 'purple', icons: [F, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'You may splay left any one color of your cards.', textJa: 'あなたは、自分のカードのうち1色を左にスプレイしてもよい。' }, { demand: false, icon: B, text: 'You may score a card from your hand.', textJa: 'あなたは手札からカードを1枚得点してもよい。' }] },
    { id: 'monotheism', name: '一神教', age: 2, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: true, icon: C, text: 'I DEMAND you transfer a top card on your board of a different color from any card on my board to my score pile! If you do, draw and tuck a 1!', textJa: '【強制】対象プレイヤーは、あなたのボードにあるどの色とも異なる色のボード上の一番上のカードを、あなたの得点パイルに渡す。渡した場合、対象プレイヤーは1を引いてタックする。' }] },
    { id: 'road_building', name: '道路建設', age: 2, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: false, icon: T, text: 'You may meld a card from your hand of value one lower than a card on your board.', textJa: 'あなたは、自分のボードにあるカードより価値が1低いカードを手札からメルドしてもよい。' }] },

    // ---------------- AGE 3 (10 cards) ----------------
    { id: 'alchemy', name: '錬金術', age: 3, color: 'purple', icons: [F, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Draw a card of value one higher than the highest top card on your board, and meld it.', textJa: '自分のボードの一番上のカードのうち最高値のものより価値が1高いカードを引き、メルドする。' }] },
    { id: 'compass', name: '羅針盤', age: 3, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may meld a card from your hand. If you do, draw and score a 3.', textJa: 'あなたは手札からカードを1枚メルドしてもよい。した場合、3を引いて得点する。' }] },
    { id: 'education', name: '教育', age: 3, color: 'blue', icons: [B, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Draw and meld a card of value one higher than your highest top card.', textJa: '自分の一番上のカードのうち最高値のものより価値が1高いカードを引いてメルドする。' }] },
    { id: 'feudalism', name: '封建制', age: 3, color: 'red', icons: [T, null, null, C],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you transfer a card with a castle icon from your hand to my hand! If you do, score your lowest card in hand.', textJa: '【強制】対象プレイヤーは、城アイコン付きカードを手札からあなたの手札に渡す。渡した場合、対象プレイヤーは自分の手札の最低値カードを得点する。' }] },
    { id: 'gunpowder', name: '火薬', age: 4, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you transfer the highest value top card on your board with a castle icon to my score pile! If you do, you may return a card from your hand.', textJa: '【強制】対象プレイヤーは、城アイコンを持つボード上の一番上のカードのうち最高値のものを、あなたの得点パイルに渡す。渡した場合、対象プレイヤーは手札からカードを1枚戻してもよい。' }] },
    { id: 'optics', name: '光学', age: 3, color: 'green', icons: [L, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'Draw a 3. If it has a crown icon, score it and meld a card from your hand. Otherwise, meld it.', textJa: '3を引く。王冠アイコンを持っていれば、それを得点し、さらに手札からカードを1枚メルドする。持っていなければ、それをメルドする。' }] },
    { id: 'paper', name: '紙', age: 3, color: 'yellow', icons: [C, null, null, B],
      dogma: [{ demand: false, icon: C, text: 'You may score a card from your hand with a crown icon. If you do, score an additional card from your hand for each crown icon on the card you scored, beyond the first.', textJa: 'あなたは、王冠アイコン付きカードを手札から1枚得点してもよい。した場合、得点したカードの王冠アイコンの数（1個目を除く）と同じ枚数のカードを手札から追加で得点する。' }] },
    { id: 'translation', name: '翻訳', age: 3, color: 'green', icons: [L, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Meld any number of top cards from your score pile with the highest value in your score pile. Claim the World special achievement if eligible.', textJa: '得点パイルの一番上のカードのうち、得点パイル内で最高値のものを好きな数メルドする。条件を満たせば世界特別達成カードを獲得する。' }] },
    { id: 'machinery', name: '機械', age: 3, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND we trade our highest value top cards with a castle icon! If you have no such card, I draw and meld a 1.', textJa: '【強制】あなたと対象プレイヤーは、城アイコンを持つ一番上のカードのうち最高値のものを交換する。対象プレイヤーがそのようなカードを持っていない場合、あなたが1を引いてメルドする。' }] },
    { id: 'colonialism', name: '植民地主義', age: 3, color: 'yellow', icons: [C, null, null, T],
      dogma: [{ demand: false, icon: T, text: 'You may return a card from your hand. If you do, draw and tuck a card of value one higher than the card you returned.', textJa: 'あなたは手札からカードを1枚戻してもよい。した場合、戻したカードより価値が1高いカードを引いてタックする。' }] },

    // ---------------- AGE 4 (10 cards) ----------------
    { id: 'anatomy', name: '解剖学', age: 4, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you return a top card from your score pile. If you do, I return the lowest card in my score pile.', textJa: '【強制】対象プレイヤーは、得点パイルの一番上のカードを1枚戻す。戻した場合、あなたは自分の得点パイルの最低値カードを戻す。' }] },
    { id: 'invention', name: '発明', age: 4, color: 'green', icons: [L, B, null, F],
      dogma: [{ demand: false, icon: B, text: 'You may splay right any one color of your cards currently splayed left. If you do, draw and score a 4.', textJa: 'あなたは、左にスプレイしている色のうち1つを右にスプレイしてもよい。した場合、4を引いて得点する。' }, { demand: false, icon: B, text: 'If you have five colors splayed, each in any direction, claim the Wonder achievement.', textJa: '5色すべてを（方向は問わず）スプレイしていれば、驚異達成カードを獲得する。' }] },
    { id: 'navigation', name: '航海術', age: 4, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'Take a 2 from the supply, then take a 1 from the supply, before drawing further cards this turn.', textJa: '補充パイルから2を1枚取り、続けて1を1枚取る。これはこのターンの他のカードを引く処理より先に行う。' }] },
    { id: 'perspective', name: '遠近法', age: 4, color: 'yellow', icons: [C, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'You may return a card from your hand. If you do, score a card from your hand for every two lightbulb icons on your board.', textJa: 'あなたは手札からカードを1枚戻してもよい。した場合、ボード上の電球アイコン2個につき手札からカードを1枚得点する。' }] },
    { id: 'printing_press', name: '活版印刷', age: 4, color: 'yellow', icons: [C, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'If you have at least 4 cards in your hand, you may return all cards in your hand. If you do, draw and score a 4 for each card you returned this way (up to a max determined by your hand size).', textJa: '手札が4枚以上あれば、手札のカードをすべて戻してもよい。した場合、戻した枚数分だけ4を引いて得点する。' }] },
    { id: 'reformation', name: '宗教改革', age: 4, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: F, text: 'You may splay your yellow or purple cards left. If you do, draw and score a 4 for every two colors you have splayed left.', textJa: 'あなたは黄または紫のカードを左にスプレイしてもよい。した場合、左にスプレイしている色2つにつき4を引いて得点する。' }] },
    { id: 'chivalry', name: '騎士道', age: 4, color: 'red', icons: [T, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you transfer your highest value top card to my board, and I draw and tuck a card of the same value! If you do, draw a 1.', textJa: '【強制】対象プレイヤーは、一番上のカードのうち最高値のものをあなたのボードに渡す。あなたは同じ価値のカードを引いてタックする。渡された場合、対象プレイヤーは1を引く。' }] },
    { id: 'experimentation', name: '実験', age: 4, color: 'green', icons: [L, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Draw and meld a 5.', textJa: '5を引いてメルドする。' }] },
    { id: 'enterprise', name: '企業', age: 4, color: 'yellow', icons: [C, null, null, T],
      dogma: [{ demand: true, icon: T, text: 'I DEMAND you transfer a top card with a castle icon from your board to my board! If you do, you may return a card from your hand, then draw and meld a card of the same value.', textJa: '【強制】対象プレイヤーは、城アイコン付きの一番上のカードをボードからあなたのボードに渡す。渡した場合、対象プレイヤーは手札からカードを1枚戻してもよく、した場合は同じ価値のカードを引いてメルドする。' }] },
    { id: 'vaccination', name: 'ワクチン', age: 3, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may return a card from your hand. If you do, draw and score a card of value one higher than the card you returned.', textJa: 'あなたは手札からカードを1枚戻してもよい。した場合、戻したカードより価値が1高いカードを引いて得点する。' }] },

    // ---------------- AGE 5 (10 cards) ----------------
    { id: 'astronomy', name: '天文学', age: 5, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return a card from your hand of value 5 or less. If you do, draw and score two cards of value one higher than the card you returned. Claim the Universe special achievement if eligible.', textJa: 'あなたは手札から価値5以下のカードを1枚戻してもよい。した場合、戻したカードより価値が1高いカードを2枚引いて得点する。条件を満たせば宇宙特別達成カードを獲得する。' }] },
    { id: 'banking', name: '銀行', age: 5, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: F, text: 'Score the lowest card on your board with a crown icon. Then, score a card from your hand for every two crown icons on your board.', textJa: 'ボード上で王冠アイコンを持つ最低値のカードを得点する。その後、ボード上の王冠アイコン2個につき手札からカードを1枚得点する。' }] },
    { id: 'chemistry', name: '化学', age: 5, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may return a card from your hand. If you do, draw and meld a card of value two higher than the card you returned, then claim the Wonder achievement if eligible.', textJa: 'あなたは手札からカードを1枚戻してもよい。した場合、戻したカードより価値が2高いカードを引いてメルドし、条件を満たせば驚異達成カードを獲得する。' }] },
    { id: 'coal', name: '石炭', age: 5, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you transfer the highest value card in your score pile to my score pile! If you do, draw a 5.', textJa: '【強制】対象プレイヤーは、得点パイルの最高値カードをあなたの得点パイルに渡す。渡した場合、対象プレイヤーは5を引く。' }] },
    { id: 'measurement', name: '測定', age: 5, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may splay any one of your colors left, right, or up. If you do, draw a 1.', textJa: 'あなたは、自分のカードのうち1色を左・右・上のいずれかにスプレイしてもよい。した場合、1を引く。' }] },
    { id: 'physics', name: '物理学', age: 5, color: 'blue', icons: [B, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'Draw three 5s. If two or more of those cards share a color, return all but one of that color and draw a card of one higher value for each card returned this way.', textJa: '5を3枚引く。そのうち2枚以上が同じ色であれば、その色のカードを1枚を除いてすべて戻し、戻した枚数分だけ価値が1高いカードを引く。' }] },
    { id: 'statistics', name: '統計学', age: 5, color: 'yellow', icons: [C, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you return a top card from your board! If you do, I return a top card from my board.', textJa: '【強制】対象プレイヤーは、ボードの一番上のカードを1枚戻す。戻した場合、あなたも自分のボードの一番上のカードを1枚戻す。' }] },
    { id: 'pirate_code', name: '海賊の掟', age: 5, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you transfer all cards in your score pile of value 5 or less to my score pile! Arrrrrr!', textJa: '【強制】対象プレイヤーは、得点パイルにある価値5以下のカードをすべてあなたの得点パイルに渡す！' }] },
    { id: 'steam_engine', name: '蒸気機関', age: 5, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND we exchange highest value cards on our boards of the same color, if possible! Repeat for each color we have in common.', textJa: '【強制】あなたと対象プレイヤーは、可能であれば同じ色のボード上の最高値カードを交換する。共有している色ごとにこれを繰り返す。' }] },
    { id: 'university', name: '大学', age: 5, color: 'green', icons: [L, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'You may return a card from your hand. If you do, draw and meld a card of value one higher than the card you returned, then draw a 1.', textJa: 'あなたは手札からカードを1枚戻してもよい。した場合、戻したカードより価値が1高いカードを引いてメルドし、さらに1を引く。' }] },

    // ---------------- AGE 6 (10 cards) ----------------
    { id: 'atomic_theory', name: '原子論', age: 6, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may splay your blue cards right. Draw and meld a 7.', textJa: 'あなたは青のカードを右にスプレイしてもよい。7を引いてメルドする。' }] },
    { id: 'classification', name: '分類法', age: 6, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'Reveal the highest valued card in your hand and score pile. Then transfer all cards of that color from your hand to your score pile.', textJa: '手札と得点パイルの中で最高値のカードを公開する。その後、その色のカードをすべて手札から得点パイルに移す。' }] },
    { id: 'democracy', name: '民主主義', age: 6, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return any number of cards from your hand. If you do, draw and meld a card of value equal to the number of cards you returned, then draw an 8.', textJa: 'あなたは手札から好きな数のカードを戻してもよい。した場合、戻した枚数と同じ価値のカードを引いてメルドし、さらに8を引く。' }] },
    { id: 'encyclopedia', name: '百科事典', age: 6, color: 'blue', icons: [B, null, null, B],
      dogma: [{ demand: false, icon: B, text: 'Meld the highest and the lowest cards in your hand.', textJa: '手札の最高値カードと最低値カードをメルドする。' }] },
    { id: 'explosives', name: '爆薬', age: 6, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you transfer the top card of your lowest value color to my score pile! If you do, draw a 6.', textJa: '【強制】対象プレイヤーは、最も価値が低い色の一番上のカードをあなたの得点パイルに渡す。渡した場合、対象プレイヤーは6を引く。' }] },
    { id: 'lensmaking', name: 'レンズ製作', age: 6, color: 'blue', icons: [B, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may splay any one of your colors left. If you do, draw and score a 6.', textJa: 'あなたは、自分のカードのうち1色を左にスプレイしてもよい。した場合、6を引いて得点する。' }] },
    { id: 'metric_system', name: 'メートル法', age: 6, color: 'yellow', icons: [C, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may splay any one of your colors right. If you do, draw a card of value equal to the number of differently colored cards you have splayed right, then meld it.', textJa: 'あなたは、自分のカードのうち1色を右にスプレイしてもよい。した場合、右にスプレイしている色の数と同じ価値のカードを引き、メルドする。' }] },
    { id: 'emancipation', name: '解放', age: 6, color: 'purple', icons: [F, null, null, C],
      dogma: [
        { demand: true, icon: C, text: 'I DEMAND you transfer a card from your hand to my score pile! If you do, draw a 1!', textJa: '【強制】対象プレイヤーは、手札からカードを1枚あなたの得点パイルに渡す。渡した場合、対象プレイヤーは1を引く。' },
        { demand: false, icon: C, text: 'You may splay your red or purple cards to the right.', textJa: 'あなたは赤または紫のカードを右にスプレイしてもよい。' }
      ] },
    { id: 'fertilizer', name: '肥料', age: 6, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may return up to two cards from your hand. If you returned any, score a card from your hand for every two cards you returned, then draw a 1.', textJa: 'あなたは手札から最大2枚のカードを戻してもよい。1枚以上戻した場合、戻した枚数2枚につき手札からカードを1枚得点し、さらに1を引く。' }] },
    { id: 'canning', name: '缶詰', age: 6, color: 'red', icons: [T, null, null, C],
      dogma: [{ demand: true, icon: C, text: 'I DEMAND you transfer a card from your score pile to my score pile! If you do, draw a 6.', textJa: '【強制】対象プレイヤーは、得点パイルからカードを1枚あなたの得点パイルに渡す。渡した場合、対象プレイヤーは6を引く。' }] },

    // ---------------- AGE 7 (10 cards) ----------------
    { id: 'bicycle', name: '自転車', age: 7, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw and meld a 7 for each two clock icons you have, up to a maximum of three times.', textJa: 'あなたが持つ時計アイコン2個につき7を引いてメルドする（最大3回まで）。' }] },
    { id: 'combustion', name: '燃焼', age: 7, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you transfer the top non-military card with the highest value to my score pile! If you do, draw a 7.', textJa: '【強制】対象プレイヤーは、軍事アイコンを持たない一番上のカードのうち最高値のものをあなたの得点パイルに渡す。渡した場合、対象プレイヤーは7を引く。' }] },
    { id: 'electricity', name: '電気', age: 7, color: 'blue', icons: [B, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you return all cards in your score pile of value 1 or 2! If you do, draw a 1 for each card returned.', textJa: '【強制】対象プレイヤーは、得点パイルにある価値1または2のカードをすべて戻す。戻した場合、戻した枚数分だけ1を引く。' }] },
    { id: 'evolution', name: '進化論', age: 7, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may return a card from your hand. If you do, draw a card of value two higher than the card you returned and meld it; otherwise draw and score a 1.', textJa: 'あなたは手札からカードを1枚戻してもよい。した場合、戻したカードより価値が2高いカードを引いてメルドする。しなかった場合は1を引いて得点する。' }] },
    { id: 'lighting', name: '照明', age: 7, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may splay any one of your colors up. If you do, draw and score a 7.', textJa: 'あなたは、自分のカードのうち1色を上にスプレイしてもよい。した場合、7を引いて得点する。' }] },
    { id: 'publication', name: '出版', age: 7, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'If you have the highest score, claim the Wonder special achievement if eligible. Then, you may return a card from your hand to draw and score a card one value higher.', textJa: 'あなたの得点が最も高ければ、条件を満たせば驚異特別達成カードを獲得する。その後、手札からカードを1枚戻して、価値が1高いカードを引いて得点してもよい。' }] },
    { id: 'railroad', name: '鉄道', age: 7, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Meld any number of cards from your hand of the same color. If you melded two or more, draw and score a card of value equal to the number of cards melded.', textJa: '手札から同じ色のカードを好きな数メルドする。2枚以上メルドした場合、メルドした枚数と同じ価値のカードを引いて得点する。' }] },
    { id: 'refrigeration', name: '冷蔵', age: 7, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may return a card from your hand. If you do, draw and meld a card of value one higher, then draw a 1.', textJa: 'あなたは手札からカードを1枚戻してもよい。した場合、価値が1高いカードを引いてメルドし、さらに1を引く。' }] },
    { id: 'sanitation', name: '公衆衛生', age: 7, color: 'purple', icons: [F, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may meld a card from your hand. If you do, score the lowest card on your board with a clock icon.', textJa: 'あなたは手札からカードを1枚メルドしてもよい。した場合、ボード上で時計アイコンを持つ最低値のカードを得点する。' }] },
    { id: 'telegraph', name: '電信', age: 7, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND we exchange the highest value top card on our boards of the same color, if possible!', textJa: '【強制】あなたと対象プレイヤーは、可能であれば同じ色のボード上の最高値の一番上のカードを交換する。' }] },

    // ---------------- AGE 8 (10 cards) ----------------
    { id: 'antibiotics', name: '抗生物質', age: 8, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: true, icon: F, text: 'I DEMAND you transfer the top card on your board of your least represented color to my score pile! If you do, draw an 8.', textJa: '【強制】対象プレイヤーは、自分のボードで最も枚数の少ない色の一番上のカードをあなたの得点パイルに渡す。渡した場合、対象プレイヤーは8を引く。' }] },
    { id: 'corporations', name: '大企業', age: 8, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may return up to three cards from your hand. If you returned any, draw and meld a card of value equal to the number of cards returned.', textJa: 'あなたは手札から最大3枚のカードを戻してもよい。1枚以上戻した場合、戻した枚数と同じ価値のカードを引いてメルドする。' }] },
    { id: 'empiricism', name: '経験主義', age: 8, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Reveal cards from the deck until you reveal one that shares a color with a top card on your board. Meld it, return the rest to the bottom of their piles.', textJa: '山札からカードを公開し続け、自分のボードの一番上のカードと同じ色のカードが出るまで続ける。そのカードをメルドし、残りは各補充パイルの底に戻す。' }] },
    { id: 'refining', name: '精製', age: 8, color: 'green', icons: [L, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'Reveal the top card of your highest value color. Score a card from your hand of that color for each top card you have of that color.', textJa: '自分の最高値の色の一番上のカードを公開する。その色の一番上のカードの枚数につき、手札からその色のカードを1枚得点する。' }] },
    { id: 'flight', name: '飛行', age: 8, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw and meld a 9.', textJa: '9を引いてメルドする。' }] },
    { id: 'mass_media', name: 'マスメディア', age: 8, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may return the two lowest cards in your hand. If you do, draw and score an 8.', textJa: 'あなたは手札の最低値カード2枚を戻してもよい。した場合、8を引いて得点する。' }] },
    { id: 'skyscrapers', name: '高層建築', age: 8, color: 'red', icons: [T, null, null, F],
      dogma: [{ demand: false, icon: F, text: 'You may meld a card from your hand with a castle or factory icon. If you do, draw and score an 8.', textJa: 'あなたは、城または工場アイコン付きのカードを手札から1枚メルドしてもよい。した場合、8を引いて得点する。' }] },
    { id: 'quantum_theory', name: '量子論', age: 8, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Return the two lowest cards in your hand. Draw and meld a card of value equal to the higher value you returned, plus one.', textJa: '手札の最低値カード2枚を戻す。戻したカードのうち高い方の価値より1高いカードを引いてメルドする。' }] },
    { id: 'socialism', name: '社会主義', age: 8, color: 'purple', icons: [F, null, null, C],
      dogma: [{ demand: false, icon: C, text: 'You may exchange your hand with any other player\'s hand who has fewer cards in hand than you.', textJa: 'あなたは、自分より手札が少ない他のプレイヤーを選び、その手札と自分の手札を交換してもよい。' }] },
    { id: 'rocketry', name: 'ロケット工学', age: 8, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND you transfer your highest value card in hand to my hand! If you do, draw an 8.', textJa: '【強制】対象プレイヤーは、手札の最高値カードをあなたの手札に渡す。渡した場合、対象プレイヤーは8を引く。' }] },

    // ---------------- AGE 9 (10 cards) ----------------
    { id: 'collaboration', name: '協調', age: 9, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw a 9.', textJa: '9を引く。' }] },
    { id: 'composites', name: '複合材料', age: 9, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may return the highest card in your hand to draw and score a 9, repeat for the next highest, up to a maximum of three cards.', textJa: 'あなたは手札の最高値カードを戻して9を引いて得点してもよい。これを次に高いカードについて繰り返す（最大3枚まで）。' }] },
    { id: 'computers', name: 'コンピュータ', age: 9, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may meld a card from your hand. If you do, draw and meld a 10.', textJa: 'あなたは手札からカードを1枚メルドしてもよい。した場合、10を引いてメルドする。' }] },
    { id: 'ecology', name: '生態学', age: 9, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND you return all top cards on your board with value 8 or less that share a color with one of my top cards! If you do, draw a card for each card returned.', textJa: '【強制】対象プレイヤーは、あなたの一番上のカードのいずれかと同じ色で、価値8以下のボード上の一番上のカードをすべて戻す。戻した場合、対象プレイヤーは戻した枚数分のカードを引く。' }] },
    { id: 'fission', name: '核分裂', age: 9, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND that, if you have two top cards with a castle icon, every player including me remove all cards from their hand, score pile, and board, and we each draw and meld a 10. Otherwise, I draw and meld a 10.', textJa: '【強制】対象プレイヤーが城アイコンを持つ一番上のカードを2枚持っている場合、あなたを含むすべてのプレイヤーは手札・得点パイル・ボードのカードをすべてゲームから除外し、各プレイヤーが10を引いてメルドする。そうでない場合、あなたが10を引いてメルドする。' }] },
    { id: 'satellites', name: '人工衛星', age: 9, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Return all cards in your hand and score pile, then draw 3 cards of value 9.', textJa: '手札と得点パイルのカードをすべて戻し、その後9を3枚引く。' }] },
    { id: 'specialization', name: '専門化', age: 9, color: 'purple', icons: [F, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Reveal the top card of each of your colors. Score a card from your hand for each revealed card that shares a color with your most numerous board color.', textJa: '自分の各色の一番上のカードを公開する。自分のボードで最も枚数が多い色と同じ色だった公開カード1枚につき、手札からカードを1枚得点する。' }] },
    { id: 'radio', name: '無線', age: 9, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Reveal cards from the deck until revealing a 10. Score it, return the rest to the bottom of their piles.', textJa: '山札からカードを公開し続け、10が出るまで続ける。それを得点し、残りは各補充パイルの底に戻す。' }] },
    { id: 'telephone', name: '電話', age: 9, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may return a card from your hand. If you do, draw and score two cards of value one higher than the card you returned.', textJa: 'あなたは手札からカードを1枚戻してもよい。した場合、戻したカードより価値が1高いカードを2枚引いて得点する。' }] },
    { id: 'suburbia', name: '郊外', age: 9, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may meld a card from your hand. If you do, score a card from your hand for each color you have at least 3 cards of on your board.', textJa: 'あなたは手札からカードを1枚メルドしてもよい。した場合、ボード上に3枚以上あるカードを持つ色1つにつき、手札からカードを1枚得点する。' }] },

    // ---------------- AGE 10 (10 cards) ----------------
    { id: 'artificial_intelligence', name: 'A.I.', age: 10, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw and meld a 10.', textJa: '10を引いてメルドする。' }] },
    { id: 'bioengineering', name: '生体工学', age: 10, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw a 10.', textJa: '10を引く。' }] },
    { id: 'globalization', name: 'グローバル化', age: 10, color: 'purple', icons: [F, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw and meld a 10.', textJa: '10を引いてメルドする。' }] },
    { id: 'miniaturization', name: '小型化', age: 10, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND you transfer the top card with the lowest value from your board to my score pile! If you do, draw a 1.', textJa: '【強制】対象プレイヤーは、ボード上の一番上のカードのうち最低値のものをあなたの得点パイルに渡す。渡した場合、対象プレイヤーは1を引く。' }] },
    { id: 'robotics', name: 'ロボット工学', age: 10, color: 'red', icons: [T, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You do not execute the non-demand effects of other players\' Robotics or Software dogma actions. Draw and meld a 10.', textJa: '他のプレイヤーが発動した「ロボット工学」または「ソフトウェア」のドグマの非強制効果は実行しない。10を引いてメルドする。' }] },
    { id: 'self_service', name: 'セルフサービス', age: 10, color: 'purple', icons: [F, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You do not execute the non-demand effects of other players\' dogma actions on cards melded since this card. Draw a 1.', textJa: 'このカードがメルドされた後にメルドされたカードによる、他のプレイヤーのドグマの非強制効果は実行しない。1を引く。' }] },
    { id: 'software10', name: 'ソフトウェア', age: 10, color: 'blue', icons: [B, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You do not execute the non-demand effects of other players\' second dogma action this turn. Draw and meld a 10.', textJa: 'このターン中、他のプレイヤーの2番目のドグマ行動による非強制効果は実行しない。10を引いてメルドする。' }] },
    { id: 'stem_cells10', name: '幹細胞', age: 10, color: 'green', icons: [L, null, null, K],
      dogma: [{ demand: true, icon: K, text: 'I DEMAND you transfer the highest card in your hand to my hand! If you do, draw a 10.', textJa: '【強制】対象プレイヤーは、手札の最高値カードをあなたの手札に渡す。渡した場合、対象プレイヤーは10を引く。' }] },
    { id: 'the_internet', name: 'インターネット', age: 10, color: 'yellow', icons: [C, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'You may exchange your highest top card with any other player\'s lowest top card of the same color, if any.', textJa: 'あなたは、自分の一番上の最高値カードを、同じ色を持つ他のプレイヤーの一番上の最低値カードと交換してもよい（あれば）。' }] },
    { id: 'nanotechnology', name: 'ナノテクノロジー', age: 10, color: 'purple', icons: [F, null, null, K],
      dogma: [{ demand: false, icon: K, text: 'Draw and score a 10 for every two factory icons you have, up to a maximum of three times.', textJa: 'あなたが持つ工場アイコン2個につき10を引いて得点する（最大3回まで）。' }] }
  ];

  return CARDS;
});
